name: Test

on:
  push:

jobs:

  test:
    runs-on: marketdb
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: |
          ls -la
          pwd
          date 
          date >> date.txt
          cal 2025 > cal.txt
          whoami

      
          
