name: Test

on:
  push:

jobs:

  job1:
    runs-on: marketdb
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: |
          ls -la
          pwd
          date 
          date >> date.txt
          cal 2025 > cal.txt
          whoami

  job2:
    runs-on: marketdb
    steps:
      - name: Run
        run: |
          ls -la
          pwd


  job3:
    runs-on: marketdb
    steps:
      - name: Run
        run: |
          ls -la
          pwd
