name: Test

on:
  push:

jobs:

  job1:
    name: Job 1
    runs-on: marketdb
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: |
          ls -la
          pwd
          date 
          date >> date.txt
          cal 2025 > cal.txt
          whoami

          
      - name: Check Python version
        run: |
          python --version
          which python

  job2:
    name: Job 2
    runs-on: marketdb
    steps:
      - name: Run
        run: |
          ls -la
          pwd


  job3:
    name: Job 3
    runs-on: marketdb
    steps:
      - name: Run
        run: |
          ls -la
          pwd
          env
