name: Test

on:
  push:

jobs:

  test:
    runs-on: marketdb
    steps:

      - name: Run
        run: |
          ls -la
          pwd
          date
          cal 2025 > cal.txt
          whoami
          
