name: Test

on:
  push:

jobs:

  test:
    runs-on: marketdb
    steps:

      - name: Run
        run: |
          ls -la
          pwd
          date 
          date >> date.txt
          cal 2025 > cal.txt
          whoami
          ping 1.1.1.1 -c 100

      
          
